/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssociationRouteImport } from './routes/association'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiNewsletterSubscribeRouteImport } from './routes/api/newsletter/subscribe'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminBootstrapRouteImport } from './routes/api/admin/bootstrap'
import { Route as ApiAdminSubscribersIndexRouteImport } from './routes/api/admin/subscribers/index'
import { Route as ApiAdminSubscribersExportRouteImport } from './routes/api/admin/subscribers/export'
import { Route as ApiAdminSubscribersIdRouteImport } from './routes/api/admin/subscribers/$id'

const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssociationRoute = AssociationRouteImport.update({
  id: '/association',
  path: '/association',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewsletterSubscribeRoute = ApiNewsletterSubscribeRouteImport.update({
  id: '/api/newsletter/subscribe',
  path: '/api/newsletter/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBootstrapRoute = ApiAdminBootstrapRouteImport.update({
  id: '/api/admin/bootstrap',
  path: '/api/admin/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscribersIndexRoute =
  ApiAdminSubscribersIndexRouteImport.update({
    id: '/api/admin/subscribers/',
    path: '/api/admin/subscribers/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSubscribersExportRoute =
  ApiAdminSubscribersExportRouteImport.update({
    id: '/api/admin/subscribers/export',
    path: '/api/admin/subscribers/export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminSubscribersIdRoute = ApiAdminSubscribersIdRouteImport.update({
  id: '/api/admin/subscribers/$id',
  path: '/api/admin/subscribers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/admin/subscribers/$id': typeof ApiAdminSubscribersIdRoute
  '/api/admin/subscribers/export': typeof ApiAdminSubscribersExportRoute
  '/api/admin/subscribers/': typeof ApiAdminSubscribersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/admin/subscribers/$id': typeof ApiAdminSubscribersIdRoute
  '/api/admin/subscribers/export': typeof ApiAdminSubscribersExportRoute
  '/api/admin/subscribers': typeof ApiAdminSubscribersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/association': typeof AssociationRoute
  '/contact': typeof ContactRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/api/admin/bootstrap': typeof ApiAdminBootstrapRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/newsletter/subscribe': typeof ApiNewsletterSubscribeRoute
  '/api/admin/subscribers/$id': typeof ApiAdminSubscribersIdRoute
  '/api/admin/subscribers/export': typeof ApiAdminSubscribersExportRoute
  '/api/admin/subscribers/': typeof ApiAdminSubscribersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/association'
    | '/contact'
    | '/evenements'
    | '/galerie'
    | '/admin/login'
    | '/admin/newsletter'
    | '/api/admin/bootstrap'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/newsletter/subscribe'
    | '/api/admin/subscribers/$id'
    | '/api/admin/subscribers/export'
    | '/api/admin/subscribers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/association'
    | '/contact'
    | '/evenements'
    | '/galerie'
    | '/admin/login'
    | '/admin/newsletter'
    | '/api/admin/bootstrap'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/newsletter/subscribe'
    | '/api/admin/subscribers/$id'
    | '/api/admin/subscribers/export'
    | '/api/admin/subscribers'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/association'
    | '/contact'
    | '/evenements'
    | '/galerie'
    | '/admin/login'
    | '/admin/newsletter'
    | '/api/admin/bootstrap'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/me'
    | '/api/newsletter/subscribe'
    | '/api/admin/subscribers/$id'
    | '/api/admin/subscribers/export'
    | '/api/admin/subscribers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AssociationRoute: typeof AssociationRoute
  ContactRoute: typeof ContactRoute
  EvenementsRoute: typeof EvenementsRoute
  GalerieRoute: typeof GalerieRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  ApiAdminBootstrapRoute: typeof ApiAdminBootstrapRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiNewsletterSubscribeRoute: typeof ApiNewsletterSubscribeRoute
  ApiAdminSubscribersIdRoute: typeof ApiAdminSubscribersIdRoute
  ApiAdminSubscribersExportRoute: typeof ApiAdminSubscribersExportRoute
  ApiAdminSubscribersIndexRoute: typeof ApiAdminSubscribersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/association': {
      id: '/association'
      path: '/association'
      fullPath: '/association'
      preLoaderRoute: typeof AssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/newsletter/subscribe': {
      id: '/api/newsletter/subscribe'
      path: '/api/newsletter/subscribe'
      fullPath: '/api/newsletter/subscribe'
      preLoaderRoute: typeof ApiNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bootstrap': {
      id: '/api/admin/bootstrap'
      path: '/api/admin/bootstrap'
      fullPath: '/api/admin/bootstrap'
      preLoaderRoute: typeof ApiAdminBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscribers/': {
      id: '/api/admin/subscribers/'
      path: '/api/admin/subscribers'
      fullPath: '/api/admin/subscribers/'
      preLoaderRoute: typeof ApiAdminSubscribersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscribers/export': {
      id: '/api/admin/subscribers/export'
      path: '/api/admin/subscribers/export'
      fullPath: '/api/admin/subscribers/export'
      preLoaderRoute: typeof ApiAdminSubscribersExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscribers/$id': {
      id: '/api/admin/subscribers/$id'
      path: '/api/admin/subscribers/$id'
      fullPath: '/api/admin/subscribers/$id'
      preLoaderRoute: typeof ApiAdminSubscribersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  AssociationRoute: AssociationRoute,
  ContactRoute: ContactRoute,
  EvenementsRoute: EvenementsRoute,
  GalerieRoute: GalerieRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  ApiAdminBootstrapRoute: ApiAdminBootstrapRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiNewsletterSubscribeRoute: ApiNewsletterSubscribeRoute,
  ApiAdminSubscribersIdRoute: ApiAdminSubscribersIdRoute,
  ApiAdminSubscribersExportRoute: ApiAdminSubscribersExportRoute,
  ApiAdminSubscribersIndexRoute: ApiAdminSubscribersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
